apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
  containers:
    - name: cont1
      image: nginx
      volumeMounts: 
      - name: v1
        mountPath: /flm/dev
    - name: cont2
      image: busybox
      command: ["sh", "-c", "while true; do sleep 3600; done"]
      volumeMounts:
      - name: v1
        mountPath: /flm/test
  volumes:
    - name: v1
      emptyDir: {}
