apiVersion: v1
kind: Pod
metadata:
  name: pod-sec2
spec:
  containers:
    - name: cont1
      image: nginx
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrt
  volumes:
    - name: secret-volume
      secret:
        secretName: sec1

