apiVersion: v1
kind: Pod
metadata:
  name: nginx-env
spec:
  containers:
    - name: myapp
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
      - configMapRef:
          name: app-config
