apiVersion: v1
kind: Pod
metadata:
  name: rq-pod
  namespace: dev
spec:
  containers:
    - name: rq-cont
      image: nginx
      ports:
       - containerPort: 80
      resources:
        requests:
          memory: "200Mi"
          cpu: "500m"
        limits:
          memory: "200Mi"
          cpu: "1"
