apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "2"
    pods: "3"
    requests.memory: 200Mi
    limits.cpu: "3"
    limits.memory: 250Mi
